server:
  port: 8088

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: COMPANY-SERVICE
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company/**

        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/job/**

        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
